# For this service to function correctly, you must provide either
# "right" or "left" for the direction. Then the hex will spin the 
# amount of "angle" degrees, to the right or left, 
# depending on what you specify.  (right and left 
# is determined from the hex perspective, looking forward)
# You could also say positive and negative (for a NED coord system).  

string direction
float64 angle
---
bool suceed
